### PR TITLE
#165413113 Follow and/or unfollow user

### PR DESCRIPTION
**Pull request by AJAkimana**
#### Description

Users are a community of like-minded authors/content creators. They can follow each other to keep track of what the followers had posted. This PR is about to follow or unfollow the user

#### Type of change
N/A
#### How Has This Been Tested?
This can be  tested by visiting the following routes
```

- Follow user:   POST  /api/v1/profiles/{username}/follow
- Unfollow user:   POST  /api/v1/profiles/{username}/unfollow
- Get a list of followers : GET /api/v1/profiles/{username}/followers
- Get a list of ones that user is following:  GET /api/v1/profiles/{username}/following

```

#### Checklist:
N/A
#### Pivotal Tracker ID
[#165413113](https://www.pivotaltracker.com/n/projects/2326984/stories/165413113)

### CODE REVIEW

**Comment by ericnyirimana** [comment]
Update your branch, please.

**Comment by AJAkimana** [comment]
> Update your branch, please.

I did

**Review by Niyitangasam — APPROVED** [review]

**Review by Niyitangasam — APPROVED** [review]
It looks good.

**Review by ericnyirimana — APPROVED** [review]

**Comment by istafrica-dennw** [comment]
- Follow or unfollow user:   POST  /api/v1/profiles/follow
should be updated to reflect the action of following exactly one user
- Get list of followers : GET /api/v1/profiles/follower/list
   we are not listing a follower. we are listing followers.
                           *one profile not profiles

**Review by Niyitangasam — CHANGES_REQUESTED** [review]
Please make your endpoint descriptive.

**Review by Niyitangasam — APPROVED** [review]

**Pull request merged**
