### PR TITLE
#165413094 Add heroku app.json Documentation

### PR DESCRIPTION
**Pull request by jabichris**
#### Description

Developers need to spend less time setting up their application. This helps developers to explain their applications, setup configurations, and runtime environments in a structured way.

#### Type of change
N/A

#### How Has This Been Tested?
N/A

#### Checklist:
N/A

#### Pivotal Tracker
https://www.pivotaltracker.com/story/show/165413094

### CODE REVIEW

**Review by AJAkimana — COMMENTED** [review]
You have to beautify the code inside `buildpacks`

**Review by Kabalisa — APPROVED** [review]
@jabichris the file looks good to me.

**Comment by macphilips** [comment]
Can't seem to find the review app on Heroku @jabichris

**Comment by jabichris** [comment]
@macphilips,
That's because collaboration was made on one app. Can't find any other way to collaborate on the entire pipeline. A possible option is to transfer it but the button is deactivated.

Screen Shot 2019-04-30 at 19 11 11

**Review by AJAkimana — APPROVED** [review]

**Pull request merged**
