### PR TITLE
#165413123 Users should be able to like a specific comment

### PR DESCRIPTION
**Pull request by Niyitangasam**
#### Description

In our authors' haven project we would like to appreciate people who comment on articles by liking their views. This feature will add that functionality to our project.

#### Type of change
N/A
#### How Has This Been Tested?
This can be  tested by visiting the following routes
```

- Like a comment:   POST  /api/v1/comments/{commentId}/feedback/like
- Get likes number : GET /api/v1/comments/{commentId}/likes
- Delete likes:  DELETE /api/v1/comments/{id}

```
#### Checklist:
N/A
#### Pivotal Tracker ID
[165413123](https://www.pivotaltracker.com/n/projects/2326984/stories/165413123)

### CODE REVIEW

**Review by Kabalisa — APPROVED** [review]
@Niyitangasam good job the feature is implemented well.

**Review by AJAkimana — COMMENTED** [review]
For `likesNumber` function in helper, I suggest using `sequelize findAndCountAll` function.

**Comment by istafrica-dennw** [comment]
one comment out of many comments so change  api/v1/comment ==> api/v1/comments
Remove the verbs from endpoints naming

**Comment by istafrica-dennw** [comment]
@here
@Niyitangasam you are not done as the reviewers have not yet done approved.

**Review by AJAkimana — APPROVED** [review]
Looks great now

**Comment by Niyitangasam** [comment]
> For `likesNumber` function in helper, I suggest using `sequelize findAndCountAll` function.

**Review by Kabalisa — APPROVED** [review]

**Pull request merged**
