### PR TITLE
#165413128 Tracking comment edits

### PR DESCRIPTION
**Pull request by AJAkimana**
#### Description
This PR is about tracking the history of editing comments. Users should track every comment that was put on their articles

#### How Has This Been Tested?
-  GET ```api/v1/article/{article-slug}/comments``` Get article comments
-  GET ```/api/v1/article/{article-slug}/comments/{comment-id}/histories``` Get comment edit histories
-  PUT ``` /api/v1/article/{article-slug}/comments/{comment-id}``` Editing comment

#### Checklist:
N/A

#### Pivotal Tracker ID
[165413128](https://www.pivotaltracker.com/n/projects/2326984/stories/165413128)

### CODE REVIEW

**Review by Niyitangasam — APPROVED** [review]

**Comment by jabichris** [comment]
@AJAkimana what if the url becomes `api/v1/articles/{article-slug}/comments` for `GET` and for `PUT` `/api/v1/articles/{article-slug}/comments/{comment-id}`?

**Review by Kabalisa — CHANGES_REQUESTED** [review]
@AJAkimana good work. what I want to suggest is that you create a route to GET the comment history for a certain comment. this will help in the frontend when a user tries to see the history of their comments.

**Comment by AJAkimana** [comment]
> @AJAkimana what if the url becomes `api/v1/articles/{article-slug}/comments` for `GET` and for `PUT` `/api/v1/articles/{article-slug}/comments/{comment-id}`?

There reason for this route: we are getting comments of an article, not articles

**Comment by AJAkimana** [comment]
> @AJAkimana good work. what I want to suggest is that you create a route to GET the comment history for a certain comment. this will help in the frontend when a user tries to see the history of their comments.

Changes are done

**Pull request merged**
